# Generated by Django 5.1.3 on 2024-12-10 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=25)),
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('lastName', models.CharField(blank=True, max_length=25)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMetod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=25)),
                ('cardNum', models.CharField(max_length=16)),
                ('cvsCode', models.CharField(max_length=4)),
                ('expDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.user')),
                ('makeModel', models.CharField(max_length=40, null=True)),
                ('year', models.CharField(blank=True, max_length=4)),
                ('plateNum', models.CharField(max_length=12)),
            ],
            bases=('home.user',),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('menu', models.ManyToManyField(to='home.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.user')),
                ('address', models.CharField(max_length=200, null=True)),
                ('paymentM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.paymentmetod')),
            ],
            bases=('home.user',),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.user')),
                ('address', models.CharField(max_length=200, null=True)),
                ('phone2', models.CharField(max_length=25, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.menu')),
            ],
            bases=('home.user',),
        ),
    ]
